index:
   path: /
   controller: App\Controller\HomeController::index

acheter:
   path: /acheter
   controller: App\Controller\ProductController::index

add:
   path: /add
   controller: App\Controller\ProductController::add
