index:
   path: /
   controller: App\Controller\HomeController::index

acheter:
   path: /acheter
   controller: App\Controller\ProductController::index

add:
   path: /category
   controller: App\Controller\CategoryController::index

louer:
   path: /louer
   controller: App\Controller\LouerController::index

user_registration:
   path: /register
   controller: App\Controller\RegistrationController::register

app_login:
   path: /login
   controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
