index:
   path: /
   controller: App\Controller\HomeController::index

acheter:
   path: /acheter
   controller: App\Controller\ProductController::index

add:
   path: /category
   controller: App\Controller\CategoryController::index

louer:
   path: /louer
   controller: App\Controller\LouerController::index
